In [1]:
import numpy as np

In [2]:
X=np.array(([2,9],[1,5],[3,6]),dtype=float)
y=np.array(([92],[86],[89]),dtype=float)
print("X= ",X)
print("y= ",y)

X=  [[2. 9.]
 [1. 5.]
 [3. 6.]]
y=  [[92.]
 [86.]
 [89.]]


Normalising the vectors

In [3]:
X=X/np.amax(X,axis=0)
y=y/100
print("X= ",X)
print("y= ",y)

X=  [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
y=  [[0.92]
 [0.86]
 [0.89]]


Defining Sigmoid function

In [4]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

Defining Derivative of Sigmoid function

In [5]:
def derivatives_sigmoid(x):
    return x*(1-x)

Initialising the layer parameters

In [6]:
epoch=7000
lr=0.1
inputlayer_neurons=2
hiddenlayer_neurons=3
output_neurons=1

In [8]:
#initialising weights between input layer and hidden layer
wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
#initialising bias between input layer and hidden layer
bh=np.random.uniform(size=(1,hiddenlayer_neurons))
#initialising weights between hidden layer and output layer
wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
#initialising bias between hidden layer and output layer
bout=np.random.uniform(size=(1,output_neurons))
print("wh= ",wh)
print("bh= ",bh)
print("wout= ",wout)
print("bout= ",bout)

wh=  [[0.46939971 0.95440665 0.03066228]
 [0.83672925 0.31921664 0.83511456]]
bh=  [[0.07008203 0.29174132 0.55880662]]
wout=  [[0.29802882]
 [0.56186046]
 [0.01784337]]
bout=  [[0.32133183]]


In [9]:
for i in range(epoch):
      #dot product of inputs and weights
      hinp1=np.dot(X,wh)
      print("hinp1= ",hinp1)
      #adding bias
      hinp=hinp1+bh
      print("hinp= ",hinp)
      #activation
      hlayer_act=sigmoid(hinp)
      #dot product of hidden layer input and weights
      outinp1=np.dot(hlayer_act,wout)
      #adding bias
      outinp=outinp1+bout
      output=sigmoid(outinp)
      print("Actual output: ",output)
      print("Expected output: ",y)
      print("Propagating back the error...")
      EO=y-output
      outgrad=derivatives_sigmoid(output)
      d_output=EO*outgrad
      EH=d_output.dot(wout.T)
      hiddengrad=derivatives_sigmoid(hlayer_act)
      d_hiddenlayer=EH*hiddengrad
      wout+=hlayer_act.T.dot(d_output)*lr
      wh+=X.T.dot(d_hiddenlayer)*lr
      print("Input:\n"+str(X))
      print("Actual Output:/n"+str(y))
      print("Predicted Output:/n",output)

Streaming output truncated to the last 5000 lines.
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output:/n[[0.92]
 [0.86]
 [0.89]]
Predicted Output:/n [[0.89761189]
 [0.87521785]
 [0.89655824]]
hinp1=  [[1.26074885 1.12439505 0.91043039]
 [0.68153008 0.58677178 0.50402556]
 [1.12378842 1.31797873 0.63349011]]
hinp=  [[1.33083088 1.41613637 1.46923701]
 [0.75161212 0.8785131  1.06283218]
 [1.19387045 1.60972005 1.19229672]]
Actual output:  [[0.89761193]
 [0.87521784]
 [0.8965582 ]]
Expected output:  [[0.92]
 [0.86]
 [0.89]]
Propagating back the error...
Input:
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output:/n[[0.92]
 [0.86]
 [0.89]]
Predicted Output:/n [[0.89761193]
 [0.87521784]
 [0.8965582 ]]
hinp1=  [[1.26075398 1.12440395 0.91043335]
 [0.68153294 0.58677667 0.50402721]
 [1.12379173 1.31798559 0.63349192]]
hinp=  [[1.33083601 1.41614528 1.46923996]
 [0.75161497 0.87851799 1.06283383]
 [1.19387376 1.609726